# Generated by Django 4.2.7 on 2023-12-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_bankrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Bankrupt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bankrupt', to='transactions.bankrupt'),
        ),
    ]
