# Generated by Django 4.2.7 on 2023-12-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Bankrupt',
        ),
    ]
