# Generated by Django 4.2.8 on 2024-01-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_transfer_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transfer_account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
